volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: tickfeeddmr_production_django
    volumes:
      - production_django_media:/app/tickfeeddmr/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    healthcheck:
      test: ['CMD', 'python', 'manage.py', 'migrate', '--check']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tickfeeddmr_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/18/docker
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:7.2

  binance_stream:
    <<: *django
    image: tickfeeddmr_production_binance_stream
    volumes: []
    depends_on:
      django:
        condition: service_healthy
      redis:
        condition: service_started
    command: python manage.py stream_binance
    restart: unless-stopped

  market_data_consumer:
    <<: *django
    image: tickfeeddmr_production_market_data_consumer
    volumes: []
    depends_on:
      django:
        condition: service_healthy
      redis:
        condition: service_started
    command: python manage.py consume_market_data_stream
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: tickfeeddmr_production_celeryworker
    volumes: []
    depends_on:
      django:
        condition: service_healthy
      redis:
        condition: service_started
    command: /start-celeryworker
    restart: unless-stopped

  celerybeat:
    <<: *django
    image: tickfeeddmr_production_celerybeat
    volumes: []
    depends_on:
      django:
        condition: service_healthy
      redis:
        condition: service_started
    command: /start-celerybeat
    restart: unless-stopped
