volumes:
  tickfeeddmr_local_postgres_data: {}
  tickfeeddmr_local_postgres_data_backups: {}
  tickfeeddmr_local_redis_data: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tickfeeddmr_local_django
    container_name: tickfeeddmr_local_django
    depends_on:
      - postgres
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    healthcheck:
      test: ['CMD', 'python', 'manage.py', 'migrate', '--check']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tickfeeddmr_production_postgres
    container_name: tickfeeddmr_local_postgres
    volumes:
      - tickfeeddmr_local_postgres_data:/var/lib/postgresql/18/docker
      - tickfeeddmr_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:7.2
    container_name: tickfeeddmr_local_redis
    command: redis-server --maxmemory ${REDIS_MAXMEMORY:-512mb} --maxmemory-policy noeviction
    volumes:
      - tickfeeddmr_local_redis_data:/data

  binance_stream:
    <<: *django
    image: tickfeeddmr_local_binance_stream
    container_name: tickfeeddmr_local_binance_stream
    depends_on:
      django:
        condition: service_healthy
      redis:
        condition: service_started
    ports: []
    command: python manage.py stream_binance
    restart: unless-stopped

  market_data_consumer:
    <<: *django
    image: tickfeeddmr_local_market_data_consumer
    container_name: tickfeeddmr_local_market_data_consumer
    depends_on:
      django:
        condition: service_healthy
      redis:
        condition: service_started
    ports: []
    command: python manage.py consume_market_data_stream
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: tickfeeddmr_local_celeryworker
    container_name: tickfeeddmr_local_celeryworker
    depends_on:
      django:
        condition: service_healthy
      redis:
        condition: service_started
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: tickfeeddmr_local_celerybeat
    container_name: tickfeeddmr_local_celerybeat
    depends_on:
      django:
        condition: service_healthy
      redis:
        condition: service_started
    ports: []
    command: /start-celerybeat
