# Generated by Django 6.0.8 on 2026-08-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='символ')),
                ('display_name', models.CharField(max_length=255, verbose_name='отображаемое имя')),
                ('is_active', models.BooleanField(default=True, help_text='Ведётся ли сейчас фоновый сбор данных по этому активу. Не является признаком того, что актив всё ещё существует или торгуется у источника.', verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='ISO-код')),
                ('moex_secid', models.CharField(blank=True, help_text='Код инструмента на MOEX, если валюта там доступна.', max_length=20, verbose_name='SECID на MOEX')),
                ('source', models.CharField(choices=[('MOEX', 'Московская биржа'), ('CBR', 'Центральный банк РФ')], max_length=10, verbose_name='источник')),
            ],
            options={
                'verbose_name': 'фиатная валюта',
                'verbose_name_plural': 'фиатные валюты',
            },
        ),
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='символ')),
                ('display_name', models.CharField(max_length=255, verbose_name='отображаемое имя')),
                ('is_active', models.BooleanField(default=True, help_text='Ведётся ли сейчас фоновый сбор данных по этому активу. Не является признаком того, что актив всё ещё существует или торгуется у источника.', verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('exchange', models.CharField(max_length=50, verbose_name='биржа')),
                ('trading_pair', models.CharField(max_length=20, verbose_name='торговая пара')),
                ('provider_asset_id', models.CharField(blank=True, help_text='Необязательный id этого актива у резервного провайдера данных.', max_length=100, verbose_name='id актива у провайдера')),
            ],
            options={
                'verbose_name': 'крипто-актив',
                'verbose_name_plural': 'крипто-активы',
                'constraints': [models.UniqueConstraint(fields=('exchange', 'trading_pair'), name='unique_crypto_exchange_trading_pair')],
            },
        ),
        migrations.CreateModel(
            name='CryptoPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='цена')),
                ('volume', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='объём')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='метка времени')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='market_data.cryptoasset', verbose_name='актив')),
            ],
            options={
                'verbose_name': 'снапшот цены крипто-актива',
                'verbose_name_plural': 'снапшоты цен крипто-активов',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='crypto_snap_asset_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='FiatPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='цена')),
                ('source', models.CharField(choices=[('MOEX', 'Московская биржа'), ('CBR', 'Центральный банк РФ')], max_length=10, verbose_name='источник')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='метка времени')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='market_data.fiatcurrency', verbose_name='актив')),
            ],
            options={
                'verbose_name': 'снапшот цены валюты',
                'verbose_name_plural': 'снапшоты цен валют',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='fiat_snap_asset_ts_idx')],
            },
        ),
    ]
