# Generated by Django 6.0.8 on 2026-09-09 21:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='отображаемое имя')),
                ('is_active', models.BooleanField(default=True, help_text='Ведётся ли сейчас фоновый сбор данных по этому активу. Не является признаком того, что актив всё ещё существует или торгуется у источника.', verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('symbol', models.CharField(help_text='SECID ISS MOEX (например, SBER) — переопределяет `AssetBase.symbol`, добавляя формат-валидацию: значение подставляется в путь URL запросов к ISS (см. `providers/moex/client.py`).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='SECID MOEX: только заглавные латинские буквы и цифры, без разделителей.', regex='^[A-Z0-9]+\\Z')], verbose_name='символ')),
                ('board', models.CharField(choices=[('TQBR', 'Т+ Акции и ДР')], default='TQBR', max_length=10, verbose_name='борд')),
                ('track_trades', models.BooleanField(default=False, help_text='Полная лента сделок собирается только по избранным бумагам — объём ленты за день по ликвидной бумаге исчисляется сотнями тысяч сделок. Снимок цены борда идёт по всем активным бумагам независимо от этого флага.', verbose_name='вести ленту сделок')),
                ('last_trade_no', models.BigIntegerField(blank=True, help_text='TRADENO последней записанной сделки — с него `poll_moex_trades` продолжает дочитывание. Пусто, если лента ещё ни разу не читалась.', null=True, verbose_name='курсор ленты (TRADENO)')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
                'constraints': [models.UniqueConstraint(fields=('board', 'symbol'), name='unique_stock_board_symbol')],
            },
        ),
        migrations.CreateModel(
            name='StockPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='последняя цена')),
                ('open', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='цена открытия')),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='максимум')),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='минимум')),
                ('change', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='изменение')),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='изменение, %')),
                ('volume', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='объём (лоты)')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='оборот')),
                ('num_trades', models.PositiveIntegerField(blank=True, null=True, verbose_name='число сделок')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Время данных ISS (`UPDATETIME`), а не время формирования ответа сервером (`SYSTIME`) — разница может достигать ~15 минут, это штатная задержка данных ISS, а не баг.', verbose_name='метка времени')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='market_data.stockasset', verbose_name='актив')),
            ],
            options={
                'verbose_name': 'снапшот цены акции',
                'verbose_name_plural': 'снапшоты цен акций',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='stock_snap_asset_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'timestamp'), name='unique_stock_snapshot_asset_ts')],
            },
        ),
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.BigIntegerField(verbose_name='TRADENO')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='цена')),
                ('quantity', models.PositiveBigIntegerField(verbose_name='количество (лоты)')),
                ('side', models.CharField(choices=[('buy', 'покупка'), ('sell', 'продажа')], max_length=4, verbose_name='сторона')),
                ('period', models.CharField(blank=True, help_text="Сырое значение поля PERIOD ISS (в наблюдавшихся данных — 'S'/'N', полный список кодов ISS не документирует). Решение о фильтрации аукционных сделок сознательно отложено на этап работы с API — здесь значение сохраняется как есть, без интерпретации.", max_length=1, verbose_name='период торгов (PERIOD)')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='метка времени')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market_data.stockasset', verbose_name='актив')),
            ],
            options={
                'verbose_name': 'сделка по акции',
                'verbose_name_plural': 'сделки по акциям',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='stock_trade_asset_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'trade_id'), name='unique_stock_trade_asset_tradeno')],
            },
        ),
    ]
