# Generated by Django 6.0.8 on 2026-09-11 09:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_stockasset_stockpricesnapshot_stocktrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatcurrency',
            name='moex_secid',
        ),
        migrations.RemoveField(
            model_name='fiatcurrency',
            name='source',
        ),
        migrations.RemoveField(
            model_name='fiatpricesnapshot',
            name='source',
        ),
        migrations.AddField(
            model_name='fiatcurrency',
            name='cbr_id',
            field=models.CharField(default='', help_text='Внутренний код ЦБ РФ (атрибут ID в ответе XML_daily.asp, например R01235) — по нему опрос курсов резолвит строки ответа на эту валюту, см. `providers/cbr/client.py`.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Код ЦБ РФ: латинская R и пять цифр, например R01235.', regex='^R\\d{5}\\Z')], verbose_name='код ЦБ РФ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiatpricesnapshot',
            name='effective_date',
            field=models.DateField(db_index=True, default=datetime.date(2026, 9, 11), help_text='Официальная дата, на которую котируется курс (атрибут Date ValCurs у ЦБ РФ) — не дата фактического опроса: ЦБ публикует курс на завтрашний рабочий день заранее, вечером текущего.', verbose_name='дата курса'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='fiatpricesnapshot',
            constraint=models.UniqueConstraint(fields=('asset', 'effective_date'), name='unique_fiat_snapshot_asset_effective_date'),
        ),
    ]
