# Generated by Django 6.0.8 on 2026-09-14 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_remove_fiatcurrency_moex_secid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatcurrency',
            name='cbr_id',
            field=models.CharField(help_text='Внутренний код ЦБ РФ (атрибут ID в ответе XML_daily.asp, например R01235) — по нему опрос курсов резолвит строки', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Код ЦБ РФ: латинская R и пять цифр, например R01235.', regex='^R\\d{5}\\Z')], verbose_name='код ЦБ РФ'),
        ),
    ]
