# Generated by Django 6.0.8 on 2026-09-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_alter_fiatcurrency_cbr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopricesnapshot',
            name='side',
            field=models.CharField(blank=True, choices=[('buy', 'покупка'), ('sell', 'продажа')], help_text='Пусто у строк, записанных до этапа 8a — тогда сторона не персистилась.', max_length=4, null=True, verbose_name='сторона'),
        ),
        migrations.AddField(
            model_name='cryptopricesnapshot',
            name='trade_id',
            field=models.CharField(blank=True, help_text='`TradeEvent.trade_id` с биржи. Пусто у строк, записанных до этапа 8a. Основа идемпотентности повторного прогона консьюмера — см. `UniqueConstraint` ниже.', max_length=64, null=True, verbose_name='id сделки у биржи'),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='exchange',
            field=models.CharField(choices=[('BINANCE', 'Binance')], max_length=50, verbose_name='биржа'),
        ),
        migrations.AddConstraint(
            model_name='cryptopricesnapshot',
            constraint=models.UniqueConstraint(fields=('asset', 'trade_id'), name='unique_crypto_snapshot_asset_trade_id'),
        ),
    ]
