# Generated by Django 6.0.8 on 2026-09-17 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_cryptopricesnapshot_side_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDailyCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='торговый день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('open', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='открытие')),
                ('high', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='максимум')),
                ('low', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='минимум')),
                ('close', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='закрытие')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='объём')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_candles', to='market_data.cryptoasset', verbose_name='актив')),
            ],
            options={
                'verbose_name': 'дневная свеча крипто-актива',
                'verbose_name_plural': 'дневные свечи крипто-активов',
                'ordering': ['-date'],
                'abstract': False,
                'indexes': [models.Index(fields=['asset', '-date'], name='crypto_candle_asset_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date'), name='unique_crypto_daily_candle_asset_date')],
            },
        ),
        migrations.CreateModel(
            name='StockDailyCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='торговый день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('open', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='открытие')),
                ('high', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='максимум')),
                ('low', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='минимум')),
                ('close', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='закрытие')),
                ('volume', models.PositiveBigIntegerField(verbose_name='объём (лоты)')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='оборот')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_candles', to='market_data.stockasset', verbose_name='актив')),
            ],
            options={
                'verbose_name': 'дневная свеча акции',
                'verbose_name_plural': 'дневные свечи акций',
                'ordering': ['-date'],
                'abstract': False,
                'indexes': [models.Index(fields=['asset', '-date'], name='stock_candle_asset_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date'), name='unique_stock_daily_candle_asset_date')],
            },
        ),
    ]
