# Generated by Django 6.0.8 on 2026-09-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market_data", "0006_cryptodailycandle_stockdailycandle"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiatcurrency",
            name="history_backfilled",
            field=models.BooleanField(
                default=False,
                help_text="Показывает, загружена ли по этой валюте вся история курсов с момента её появления, а не только текущие значения за последние дни. Пока не отмечено — при ближайшем обновлении системой валюта автоматически докачает всю историю целиком, и после этого отметка проставится сама. Поле только для чтения — заполняется автоматически, вручную менять не нужно.",
                verbose_name="полная история загружена",
            ),
        ),
    ]
